import { defineType, defineField } from 'sanity';

export const blogPost = defineType({
  name: 'blogPost',
  title: 'Blog Post',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: 'title',
        maxLength: 96,
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'isFeatured',
      title: 'Featured',
      type: 'boolean',
      initialValue: false,
      description: 'Show this post as the featured article on the blog listing page',
    }),
    defineField({
      name: 'publishedAt',
      title: 'Published At',
      type: 'datetime',
    }),
    defineField({
      name: 'excerpt',
      title: 'Excerpt',
      type: 'text',
      rows: 3,
      description: 'A short summary of the blog post',
    }),
    defineField({
      name: 'readingTime',
      title: 'Reading Time (minutes)',
      type: 'number',
    }),
    defineField({
      name: 'tags',
      title: 'Tags',
      type: 'array',
      of: [
        {
          type: 'string',
          options: {
            list: [
              'Ancestral Voices',
              'Authentic Writing',
              'Awareness Narratives',
              'Beyond Chronology',
              'Biographer',
              'Biography Writing',
              'Capturing Voices',
              'Central Theme',
              'Character Development',
              'Clarity and Flow',
              'Collaborative Memoir',
              'Collaborative Writing',
              'Connections in Writing',
              'Crafting Identity',
              'Crafting Your Story',
              'Creative Drafting',
              'Creative Storytelling',
              'Cultural Heritage',
              'Cultural Identity Writing',
              'Dialogue Crafting',
              'Digital Hosting',
              'Digital Storytelling',
              'Editing Tips',
              'Embrace Your Story',
              'Emotional Intelligence',
              'Emotional Narrative',
              'Empathy in Writing',
              'Empowerment Journey',
              'Engaging Writing',
              'Everyday Moments',
              'Family Conflicts',
              'Family History',
              'Finding Significance',
              'Flashback and Foreshadowing',
              'Friendships Matter',
              'Ghost Writing',
              'Healing Through Story',
              'Heritage Exploration',
              'Hopeful Narratives',
              'Humor in Adversity',
              'Information Revelation',
              'Inner Critic',
              'Interactive Narrative',
              'Interview Crafting',
              'Learning',
              'Life Story',
              'Memoir Interviews',
              'Memoir Writing',
              'Memory',
              'Memory Elicitation',
              'Mental Health Writing',
              'Multigenerational Perspectives',
              'Narrative Crafting',
              'Narrative Depth',
              'Narrative Journey',
              'Narrative Structure',
              'Narrative Tapestry',
              'Navigating Challenges',
              'Navigating Sensitive Topics',
              'Obituary Writing',
              'Online Memoir',
              'Overcoming Adversity',
              'Personal Journey',
              'Personal Storytelling',
              'Personal Style',
              'Preserving Memories',
              'Principles',
              'Printed Memoir',
              'Privacy Protection',
              'Productivity',
              'Professional Influence',
              'Publication Readiness',
              'Rediscover Memories',
              'Resilience Stories',
              'Respectful Narrative',
              'Self Authoring',
              'Self Reflection',
              'Sensitive Storytelling',
              'Sharing Your Truth',
              'Step-by-step Guide',
              'Story Editing',
              'Story Organization',
              'Story Telling',
              'Storytelling Techniques',
              'Time Manipulation',
              'Tips & Tricks',
              'Tone & Voice',
              'Transformative Narratives',
              'Unique Voice',
              'Voices of Loved Ones',
              'Vulnerability In Writing',
              'Wisdom',
              'Writing About Pain',
              'Writing Craft',
              'Writing Decisions',
              'Writing Journey',
              'Writing Memories',
              'Writing Techniques',
              'Writing Tips',
            ],
          },
        },
      ],
      description: 'Select tags from the predefined list',
    }),
    defineField({
      name: 'topic',
      title: 'Topic',
      type: 'string',
      options: {
        list: [
          'How-to Guides',
          'Writing a Memoir',
          'Navigating Sensitive Topics',
          'From Draft to Publication',
          'Voices and Perspectives',
          'Crafting Narrative',
        ],
      },
      description: 'Primary topic category for the article',
    }),
    defineField({
      name: 'seoTitle',
      title: 'SEO Title',
      type: 'string',
      description: 'Overrides the post title for the page meta title tag',
    }),
    defineField({
      name: 'seoDescription',
      title: 'SEO Description',
      type: 'text',
      rows: 2,
      description: 'Overrides the excerpt for the page meta description tag',
    }),
    defineField({
      name: 'featuredImage',
      title: 'Featured Image',
      type: 'image',
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: 'photoCredit',
      title: 'Photo Credit',
      type: 'string',
      description: 'Photographer or image source name',
    }),
    defineField({
      name: 'photoCreditLink',
      title: 'Photo Credit Link',
      type: 'url',
      description: 'Link to the photographer or image source',
    }),
    defineField({
      name: 'author',
      title: 'Author',
      type: 'string',
    }),
    defineField({
      name: 'quote',
      title: 'Quote',
      type: 'text',
      rows: 3,
      description: 'A testimonial or pull quote featured in the article',
    }),
    defineField({
      name: 'quoteAuthor',
      title: 'Quote Author',
      type: 'string',
      description: 'Attribution for the quote',
    }),
    defineField({
      name: 'content',
      title: 'Content',
      type: 'array',
      of: [
        { type: 'block' },
        {
          type: 'image',
          options: { hotspot: true },
        },
      ],
    }),
    defineField({
      name: 'summary',
      title: 'Summary',
      type: 'array',
      of: [{ type: 'block' }],
      description: 'Summary section displayed after the article content',
    }),
    defineField({
      name: 'keyTakeaways',
      title: 'Key Takeaways',
      type: 'array',
      of: [{ type: 'block' }],
      description: 'Key takeaways section displayed at the end of the article',
    }),
  ],
  preview: {
    select: {
      title: 'title',
      media: 'featuredImage',
      author: 'author',
    },
    prepare({ title, media, author }) {
      return {
        title,
        subtitle: author ? `by ${author}` : '',
        media,
      };
    },
  },
});
